import Head from "next/head";
import styles from "../styles/Home.module.css";
import Timer from "../components/Timer/Timer";
import clsx from "clsx";
import { useAppSelector } from "../features/timer/hooks";

export default function Home() {
  const { session } = useAppSelector((state) => state.timer);

  return (
    <>
      <Head>
        <title>Pomodoro Timer</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={clsx(styles.root, styles[session.id])}>
        <div className={styles.container}>
          <Timer />
        </div>
      </main>
    </>
  );
}
